<?php

namespace PilotParc\LoginBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CodeNafRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeNafRepository extends EntityRepository
{
}
