<?php

namespace PilotParc\LoginBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EncaissementPlaceJourMarcheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncaissementPlaceJourMarcheRepository extends EntityRepository
{
}
