<?php

namespace PilotParc\LoginBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MarchandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarchandRepository extends EntityRepository
{
}
