<?php

namespace PilotParc\LoginBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MarcheJourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarcheJourRepository extends EntityRepository
{
}
